//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Malaria.Context
{
    using MalariaAPI.Models;
    using System.Data.Entity;

    public partial class MalariaContext : DbContext
    {
        public MalariaContext() : base("name=MalariaContext")
        {

        }

        public virtual DbSet<Malaria_Areas> Malaria_Areas { get; set; }
        public virtual DbSet<Malaria_Controls> Malaria_Controls { get; set; }
        public virtual DbSet<Malaria_Facts> Malaria_Facts { get; set; }
        public virtual DbSet<Malaria_Log> Malaria_Log { get; set; }
        public virtual DbSet<Malaria_Prevention> Malaria_Prevention { get; set; }
        public virtual DbSet<Malaria_Treatments> Malaria_Treatments { get; set; }
    }
}